remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Yeraldin Carvajal Granda
submodulo: Mobiles 1
periodo: 2023-2
url_foto: https://avatars.githubusercontent.com/u/143223559?s=400&u=0d6ae3c327f609e28433c7d2f8d724f04d392871&v=4
